# Generated by Django 5.2 on 2025-04-28 14:24

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='learnvideo',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='watchedvideo',
            options={'ordering': ['-last_watched_at']},
        ),
        migrations.RemoveField(
            model_name='watchedvideo',
            name='watched_at',
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon name from Lucide icons', max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which categories should appear'),
        ),
        migrations.AddField(
            model_name='learnvideo',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating (0-5)', max_digits=3),
        ),
        migrations.AddField(
            model_name='learnvideo',
            name='duration',
            field=models.DurationField(blank=True, help_text='Video duration in HH:MM:SS format', null=True),
        ),
        migrations.AddField(
            model_name='learnvideo',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learnvideo',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='learnvideo',
            name='likes',
            field=models.PositiveIntegerField(default=0, help_text='Total number of likes'),
        ),
        migrations.AddField(
            model_name='learnvideo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='learnvideo',
            name='views',
            field=models.PositiveIntegerField(default=0, help_text='Total number of views'),
        ),
        migrations.AddField(
            model_name='watchedvideo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchedvideo',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watchedvideo',
            name='last_watched_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='watchedvideo',
            name='progress',
            field=models.PositiveIntegerField(default=0, help_text='Progress percentage (0-100)'),
        ),
        migrations.CreateModel(
            name='UserLearningStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_videos_watched', models.PositiveIntegerField(default=0)),
                ('total_time_spent', models.DurationField(default=datetime.timedelta(0), help_text='Total time spent learning')),
                ('current_streak', models.PositiveIntegerField(default=0, help_text='Current daily streak')),
                ('longest_streak', models.PositiveIntegerField(default=0, help_text='Longest daily streak')),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_videos', models.PositiveIntegerField(default=0)),
                ('completed_videos', models.PositiveIntegerField(default=0)),
                ('total_time_spent', models.DurationField(default=datetime.timedelta(0), help_text='Total time spent watching videos in this category')),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='learning.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Learning Progress',
                'unique_together': {('user', 'category')},
            },
        ),
    ]
