# Generated by Django 5.2 on 2025-04-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LetterGesture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=2, unique=True)),
                ('video', models.FileField(upload_to='gestures/letters/')),
            ],
        ),
        migrations.CreateModel(
            name='WordGesture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=32, unique=True)),
                ('video', models.FileField(upload_to='gestures/words/')),
            ],
        ),
    ]
